import "../css/globals.css";
import { Inter } from "next/font/google";
import { Info_v1, Menu_v1, Footer_v1 } from "@/UI";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Info_v1 />
        <Menu_v1 />
        {children}
        <Footer_v1 />
      </body>
    </html>
  );
}
